// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fohumoowudecafbfwuir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvaHVtb293dWRlY2FmYmZ3dWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODk0NzAsImV4cCI6MjA1OTM2NTQ3MH0.bhlex9_z6pjW76ZiLQ2KIKJjkAFtj4I4pRziZoaBZvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);